### ISSUE TITLE
Configuration differences compared to original

### ISSUE THREAD

**Issue by dontub** [DanielMazurkiewicz/TevoTornadoShare#1]
I'm planning to update the firmware of my Tornado and thus have found your repo. I've seen that you've made some configuration changes compared to the original firmware. As there is no explanation for the changes I'm wondering why you have made them and if I should use them myself. Can you give some insights?

**Comment by DanielMazurkiewicz** [comment]
There is quite a lot of small changes, so would be easier for me to answer you according to particular settings. Use tools like "meld" to compare changes in configuration files. All configuration options are pretty well described in config files so you'll easily figure out why and what I've changed.

Also want to warn you here that same tevo tornado ships with different electronic boards (not all compatible with each other), so that means that you can't just use any firmware for your printer, it has to be set up specifically for your motherboard.

**Comment by dontub** [comment]
Since I'm having the older model with an MKS Base board, I'll set `MOTHERBOARD` to `BOARD_MKS_BASE` and would use values from https://github.com/tevo3d/Tevo-Tornado if I'm unsure because there `MOTHERBOARD` is set to `BOARD_MKS_BASE`, too.

However I'm especially not sure about `DEFAULT_AXIS_STEPS_PER_UNIT`. The original values are `{ 80.3190, 80.3190, 399.2901, 400 }`. I've seen different values in different configuration files out there. Though the value you used seems to be used most often, at least if `MOTHERBOARD` is not `BOARD_MKS_BASE`. But I've also seen configurations with the same steps per unit as yours with `BOARD_MKS_BASE`. Actually I can't estimate the implications.

The default accelerations are also different across the configurations I've seen, but if changed lower than the original ones. I'd assume that it would make sense to lower the values for my printer as well. The various jerk values out there also seem to be most often lower than the original ones. So I'd assume that it would make sense to reduce them in my configuration, too.

The combination of the accelerations and the jerk values seem to be unique for your configuration. Is there a special reason for the values you've chosen?

**Comment by DanielMazurkiewicz** [comment]
Steps per unit will have implications in the first place in printed object sizes as it is to define conversion between axis movement to linear movement (axis steps to linear millimeters or inches). In second place it will impact calculations of acceleration and speed. So slight differences in these values are not dangerous at all and can aim to improve print quality (eg. correct diameter of gears). Big differences have to go along with knowledge of your stepper motors, mechanical parts and configuration of your stepper drivers.

As it comes to accelerations - that impacts print speed and print quality. Too big values may make entire printer shaking and/or "spilling" melted plastic not in correct places. Too small values are not dangerous and even may improve print quality. My values are some sort of compromise between quality and speed.

**Comment by dontub** [comment]
Thanks for your detailed answers. I've decided upon the values I'm going to try and hope to get some time for it soon.
